#+STARTUP: showall

* Org-files-db                                                   :noexport_2:

[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]

=Org-files-db= stores data from Org-mode files — headings, tags, properties, links, timestamps, and keywords — in a SQLite database.

You can track individual files or directories (recursively).

The package parses the files asynchronously (non-blocking) and automatically detects changes to keep the database up to date.

-----

** Contents

- [[#installation][Installation]]
- [[#usage][Usage]]
- [[#customization][Customization]]
- [[#key-bindings][Key Bindings]]
- [[#sqlite-database-schema][SQLite Database Schema]]
- [[#changelog][Changelog]]
- [[#contributing][Contributing]]

** Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

This package is hosted on Github. Use your favourite way to install like [[https://github.com/progfolio/elpaca][Elpaca]], [[https://github.com/radian-software/straight.el][Straight]], [[https://github.com/quelpa/quelpa][Quelpa]]. Starting with Emacs 29 ~package-vc-install~ may be used.

** Usage
:PROPERTIES:
:CUSTOM_ID: usage
:END:

<Usage description>

** Customization
:PROPERTIES:
:CUSTOM_ID: customization
:END:

*** Variables

Set the following variables to change the behaviour of the package:

| Variable | Default | Description |
|----------+---------+-------------|
|          |         |             |

*** Faces

The following faces are defined:

| Face | Description |
|------+-------------|
|      |             |
|      |             |

** Key Bindings
:PROPERTIES:
:CUSTOM_ID: key-bindings
:END:

<whatever needs to be said about that>

| Key | Action | Description |
|-----+--------+-------------|
|     |        |             |

*** Hydra

<if there is any hydra>

** SQLite Database Schema
:PROPERTIES:
:CUSTOM_ID: sqlite-database-schema
:END:

The schema is documented in [[file:docs/sqlite-database-schema.org][sqlite-database-schema.org]].

** Changelog
:PROPERTIES:
:CUSTOM_ID: changelog
:END:

See the [[./CHANGELOG.org][changelog]].

** Contributing
:PROPERTIES:
:CUSTOM_ID: contributing
:END:

Use the issue tracker to reports bugs, suggest improvements or propose new
features. If you want to contribute please open a pull request after having
opened a new issue.

This project is maintained on a “best-effort” basis.

In any case please check out the [[./CONTRIBUTING.org][contributing guidelines]] beforehand.
