#+STARTUP: content

* Org-files-db                                                   :noexport_2:

[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]

Store headings and links from org files from one or more directories in a SQLite
database.

** Main features                                                :noexport_0:

- Store headings and links from org files from one or more directories in a
  SQLite database.
- For each heading it stores the filename, line number, title, level, priority,
  todo keyword, statistic cookies, planning info (scheduled, deadline, closed),
  parent heading id, tags and properties.
- For each link it stores the filename, position, full link, type, link and
  description.
- Provides queries for the most common use cases.
- Uses [[https://github.com/Genivia/ugrep][ugrep]] to quickly parse the files.
- Uses [[https://github.com/sharkdp/fd][fd]] to check if files are modified for reparsing.

-----

** Contents

- [[#installation][Installation]]
- [[#usage][Usage]]
- [[#customization][Customization]]
- [[#key-bindings][Key Bindings]]
- [[#changelog][Changelog]]
- [[#contributing][Contributing]]

** Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

The packages is available on Github. Packages from Github can be installed with
for instance [[https://github.com/quelpa/quelpa][Quelpa]] or [[https://github.com/raxod502/straight.el][Straight]]. In addition you can use [[https://github.com/jwiegley/use-package][Use-package]] or [[https://github.com/conao3/leaf.el][Leaf]] to
simplify your init file:

@@html:<details>@@
@@html:<summary>@@
With Straight
@@html:</summary>@@

- Straight
  #+BEGIN_SRC emacs-lisp
  (straight-use-package '(org-files-db :type git :host github :repo "hubisan/org-files-db"))
  #+END_SRC

- Use-package & Straight
  #+BEGIN_SRC emacs-lisp
    (use-package org-files-db
      :straight (org-files-db :type git :host github :repo "hubisan/org-files-db"))
  #+END_SRC

- Leaf & Straight
  #+BEGIN_SRC emacs-lisp
  (leaf org-files-db
      :straight (org-files-db :type git :host github :repo "hubisan/org-files-db"))
  #+END_SRC
  
@@html:</details>@@

@@html:<details>@@
@@html:<summary>@@
With Quelpa
@@html:</summary>@@

- Quelpa
  #+BEGIN_SRC emacs-lisp
    (quelpa '(org-files-db :repo "hubisan/org-files-db" :fetcher github))
  #+END_SRC

- Use-package & Quelpa
  #+BEGIN_SRC emacs-lisp
    (use-package org-files-db
      :quelpa (org-files-db :repo "hubisan/org-files-db" :fetcher github))
  #+END_SRC
@@html:</details>@@

*** Dependencies

Org-files-db depends on [[https://github.com/Genivia/ugrep][ugrep]] to parse the files, [[https://www.sqlite.org/index.html][SQLite]] for the database and [[https://github.com/sharkdp/fd][fd]]
is used to check for modified files. You have to install those three
dependencies.

** Usage
:PROPERTIES:
:CUSTOM_ID: usage
:END:

<Usage description>

** Customization
:PROPERTIES:
:CUSTOM_ID: customization
:END:

*** Variables

Set the following variables to change the behaviour of the package:

| Variable | Default | Description |
|----------+---------+-------------|
|          |         |             |

*** Faces

The following faces are defined:

| Face | Description |
|------+-------------|
|      |             |
|      |             |

** Key Bindings
:PROPERTIES:
:CUSTOM_ID: key-bindings
:END:

<whatever needs to be said about that>

| Key | Action | Description |
|-----+--------+-------------|
|     |        |             |

*** Hydra

<if there is any hydra>

** Changelog
:PROPERTIES:
:CUSTOM_ID: changelog
:END:

See the [[./CHANGELOG.org][changelog]].

** Contributing
:PROPERTIES:
:CUSTOM_ID: contributing
:END:

Use the issue tracker to reports bugs, suggest improvements or propose new
features. If you want to contribute please open a pull request after having
opened a new issue.

In any case please check out the [[./CONTRIBUTING.org][contributing guidelines]] beforehand.
