db_path = "./db/org-files-db.sqlite"

files = []

[[dirs]]
path = "./org"
recursive = true

[search]
fts5_enabled = false
index_body_text = false

[todo]
default_open_keywords = ["TODO", "NEXT"]
default_closed_keywords = ["DONE", "CANCEL"]

[query]
timezone = "Europe/Zurich"
