name: CI
# https://github.com/conao3/cort.el/blob/master/.github/workflows/test.yml

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.org'
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.org'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '27.1'
          - '27.2'
          - 'snapshot'
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Run tests
        if: matrix.allow_failure != true
        run: make test

      - name: Run tests (allow failure)
        if: matrix.allow_failure == true
        continue-on-error: true
        run: make test
        # run: make test || true

  lint:
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make prepare

      - name: Run lint
        run: make lint
