name: CI
# https://github.com/conao3/cort.el/blob/master/.github/workflows/test.yml

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.org'
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.org'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '27.1'
          - '27.2'
          - 'snapshot'

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '27.1'

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Run lint
        run: make lint
